- name: Install sslsplit
  apt:
    name: sslsplit
    state: present
    update_cache: yes

- name: Create sslsplit directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /etc/sslsplit
    - /var/log/dns/sslsplit

- name: Generate CA key
  command: openssl genrsa -out /etc/sslsplit/ca.key 4096
  args:
    creates: /etc/sslsplit/ca.key

- name: Generate CA certificate
  command: >
    openssl req -new -x509 -days 3650
    -key /etc/sslsplit/ca.key
    -out /etc/sslsplit/ca.crt
    -subj "/C=DE/ST=HH/L=HH/O=Minimal-DoT-Proxy/CN=sslsplit-ca"
  args:
    creates: /etc/sslsplit/ca.crt

- name: Create sslsplit user
  user:
    name: sslsplit
    system: yes
    shell: /usr/sbin/nologin
    create_home: no

- name: Set permissions
  file:
    path: "{{ item.path }}"
    owner: root
    group: sslsplit
    mode: "{{ item.mode }}"
  loop:
    - { path: '/etc/sslsplit', mode: '0750' }
    - { path: '/etc/sslsplit/ca.crt', mode: '0640' }
    - { path: '/etc/sslsplit/ca.key', mode: '0640' }
    - { path: '/var/log/dns/sslsplit', mode: '0750' }

- name: Create empty log files for sslsplit
  file:
    path: "{{ item }}"
    state: touch
    owner: sslsplit
    group: sslsplit
    mode: '0640'
  loop:
    - /var/log/dns/sslsplit/connections.log
    - /var/log/dns/sslsplit/keys.log

- name: Add measurement user to sslsplit group
  user:
    name: "{{ measure_user }}"
    groups: sslsplit
    append: yes
  
- name: Create empty pcap file for sslsplit
  file:
    path: /var/log/dns/sslsplit/traffic.pcap
    state: touch
    owner: sslsplit
    group: sslsplit
    mode: '0640'

- name: Create minimal sslsplit systemd service
  copy:
    dest: /etc/systemd/system/sslsplit.service
    mode: '0644'
    content: |
      [Unit]
      Description=Minimal SSLsplit DoT Proxy
      After=network-online.target

      [Service]
      ExecStart=/usr/bin/sslsplit \
        -k /etc/sslsplit/ca.key \
        -c /etc/sslsplit/ca.crt \
        -l /var/log/dns/sslsplit/connections.log \
        -X /var/log/dns/sslsplit/traffic.pcap \
        -L /var/log/dns/sslsplit/keys.log \
        -D \
        ssl 127.0.0.1 8853 9.9.9.9 853
      User=sslsplit
      Group=sslsplit
      AmbientCapabilities=CAP_NET_BIND_SERVICE
      CapabilityBoundingSet=CAP_NET_BIND_SERVICE
      NoNewPrivileges=true
      ReadWritePaths=/var/log/dns/sslsplit
      PrivateDevices=true
      PrivateTmp=true
      Restart=on-failure

      [Install]
      WantedBy=multi-user.target
  notify: Reload systemd

- name: Reload systemd
  systemd:
    daemon_reload: yes
