- hosts: client
  become: yes
  vars:
    ansible_shell_executable: /bin/bash

  pre_tasks:
    - name: Check if resolved.conf exists
      stat:
        path: /etc/systemd/resolved.conf
      register: resolved_conf

    - name: Set Temporary DNS Server for Internet Access
      lineinfile:
        path: /etc/systemd/resolved.conf
        line: "DNS=9.9.9.9"
        state: present
      when: resolved_conf.stat.exists

    - name: Restart systemd-resolved
      systemd:
        name: systemd-resolved
        state: restarted
      when: resolved_conf.stat.exists


    - name: Install git & kdig
      apt:
        name:
          - git
          - knot-dnsutils
        state: present
        update_cache: yes

    - name: Ensure /var/log/dns directory exists
      file:
        path: /var/log/dns
        state: directory
        mode: '0755'


  roles:
    - resolved
    - stubby-install
    - tcpdump
    - python
    - sslsplit
    - stubby-service
    - data

  # Enable and start all services after setting configs with roles
  post_tasks:
    - name: Enable & start core DNS services
      systemd:
        name: "{{ item }}"
        enabled: yes
        state: started
      loop:
        - systemd-resolved
        - sslsplit
        - stubby

    # - name: Enable & start dns-monitor
    #   systemd:
    #     name: dns-monitor
    #     enabled: yes
    #     state: started