# - hosts: resolver
#   become: yes
#   roles:
#     - timesync
#     - resolver

- hosts: client
  become: yes
  vars:
    ansible_shell_executable: /bin/bash
  roles:
    - timesync
    - client

# - hosts: sniffer
#   become: yes
#   roles:
#     - timesync
#     - sniffer
