- name: Configure Stubby to use Unbound proxy
  copy:
    dest: "/usr/local/etc/stubby/stubby.yml"
    mode: '0644'
    content: |
      resolution_type: GETDNS_RESOLUTION_STUB
      dns_transport_list:
        - GETDNS_TRANSPORT_TLS
      tls_authentication: GETDNS_AUTHENTICATION_NONE
      round_robin_upstreams: 1
      idle_timeout: 10000
      listen_addresses:
        - 127.0.0.1@53
      # Stubby verbindet sich mit Unbound DoT Proxy
      upstream_recursive_servers:
        - address_data: 127.0.0.1
          tls_port: 8853
          tls_auth_name: "dnsproxy.local"
      appdata_dir: "/var/log/dns/stubby"
      log_level: 7
  notify: Restart stubby

- name: Ensure only 127.0.0.1 is in /etc/resolv.conf
  lineinfile:
    path: /run/systemd/resolve/resolv.conf
    regexp: '^nameserver '
    line: 'nameserver 127.0.0.1'
    state: present
    insertafter: BOF
  notify: Reload systemd

- name: Remove all other nameservers from /run/systemd/resolve/resolv.conf
  replace:
    path: /run/systemd/resolve/resolv.conf
    regexp: '^nameserver (?!127\.0\.0\.1).*'
    replace: ''
  notify: Reload systemd
  
- name: Create stubby systemd service
  copy:
    dest: /etc/systemd/system/stubby.service
    mode: '0644'
    content: |
      [Unit]
      Description=DNS Privacy Stub Resolver
      Wants=network-online.target
      After=network-online.target
      Before=nss-lookup.target
      Wants=nss-lookup.target

      [Service]
      Type=simple
      ExecStart=/usr/local/bin/stubby -C /usr/local/etc/stubby/stubby.yml -l
      StandardOutput=append:/var/log/dns/stubby/stubby.log
      StandardError=append:/var/log/dns/stubby/stubby.log


      KillSignal=SIGINT
      Restart=on-failure
      RestartSec=5
      User=stubby
      Group=stubby
      AmbientCapabilities=CAP_NET_BIND_SERVICE
      CapabilityBoundingSet=CAP_NET_BIND_SERVICE
      NoNewPrivileges=true
      MemoryDenyWriteExecute=true
      RestrictRealtime=true
      RestrictSUIDSGID=true
      ProtectControlGroups=true
      ProtectKernelModules=true
      ProtectKernelTunables=true
      ProtectSystem=strict
      ProtectHome=true
      ReadWritePaths=/var/log/dns/stubby
      PrivateDevices=true
      PrivateTmp=true

      [Install]
      WantedBy=multi-user.target
  notify: Reload systemd

- name: Configure systemd-resolved to forward to Stubby
  block:
    - name: Ensure resolved drop-in directory exists
      file:
        path: /etc/systemd/resolved.conf.d
        state: directory
        mode: '0755'

    - name: Remove temporary DNS from resolved.conf
      lineinfile:
        path: /etc/systemd/resolved.conf
        line: "DNS=9.9.9.9"
        state: absent

    - name: Set Stubby as DNS resolver
      copy:
        dest: /etc/systemd/resolved.conf.d/stubby.conf
        mode: '0644'
        content: |
          [Resolve]
          DNS=127.0.0.1:53
          DNSStubListener=no
          Cache=no
          DNSOverTLS=no
      notify: Restart systemd-resolved

- name: Make resolv.conf managed by systemd-resolved
  file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: yes
  notify: Reload systemd

- meta: flush_handlers
