- name: Ensure Python 3 and pip are installed
  ansible.builtin.apt:
    name: python3-pip
    state: present
    update_cache: true
  become: true

- name: Ensure python3-venv is installed
  ansible.builtin.apt:
    name: python3-venv
    state: present
    update_cache: true
  become: true

- name: Create Python virtual environment
  command: python3 -m venv /opt/dns/venv
  args:
    creates: /opt/dns/venv/bin/activate

- name: Install pip in venv (ensure latest pip)
  command: /opt/dns/venv/bin/pip install --upgrade pip setuptools wheel

- name: Install required Python packages in venv
  command: /opt/dns/venv/bin/pip install dnspython pandas scapy selenium

- name: Ensure venv activation in .bashrc for vagrant user
  lineinfile:
    path: /home/vagrant/.bashrc
    insertafter: EOF
    line: 'source /opt/dns/venv/bin/activate'
    state: present
    create: yes
    owner: vagrant
    group: vagrant
    mode: '0644'

- name: Copy DNS Client Script to /opt/dns
  copy:
    src: "{{ python_source_dir}}/client.py"
    dest: /opt/dns/client.py
    mode: '0644'

- name: Copy Web DNS Client Script to /opt/dns
  copy:
    src: "{{ python_source_dir}}/webclient.py"
    dest: /opt/dns/webclient.py
    mode: '0644'


- name: Copy Metadata Extractor Script to /opt/dns
  copy:
    src: "{{ python_source_dir}}/metadata_extractor.py"
    dest: /opt/dns/metadata_extractor.py
    mode: '0644'

- name: Install Chromium browser and chromedriver
  apt:
    name:
      - chromium
      - chromium-driver
    state: present