- name: Ensure Python 3 and pip are installed
  ansible.builtin.apt:
    name: python3-pip
    state: present
    update_cache: true
  become: true

- name: Ensure python3-venv is installed
  ansible.builtin.apt:
    name: python3-venv
    state: present
    update_cache: true
  become: true

- name: Create Python virtual environment
  command: python3 -m venv /opt/dns/venv
  args:
    creates: /opt/dns/venv/bin/activate

- name: Install pip in venv (ensure latest pip)
  command: /opt/dns/venv/bin/pip install --upgrade pip setuptools wheel

- name: Install required Python packages in venv
  command: /opt/dns/venv/bin/pip install dnspython pandas scapy selenium

- name: Ensure venv activation in .bashrc for measurement user
  lineinfile:
    path: ~/.bashrc
    insertafter: EOF
    line: 'source /opt/dns/venv/bin/activate'
    state: present
    create: yes
    owner: "{{ measure_user }}"
#    group: vagrant
    mode: '0644'

- name: Copy DNS Client Script to /opt/dns
  copy:
    src: "{{ python_source_dir}}/client.py"
    dest: /opt/dns/client.py
    mode: '0644'

- name: Copy Web DNS Client Script to /opt/dns
  copy:
    src: "{{ python_source_dir}}/webclient.py"
    dest: /opt/dns/webclient.py
    mode: '0644'


- name: Copy Metadata Extractor Script to /opt/dns
  copy:
    src: "{{ python_source_dir}}/metadata_extractor.py"
    dest: /opt/dns/metadata_extractor.py
    mode: '0644'

- name: Install Chromium browser and chromedriver
  apt:
    name:
      - chromium
      - chromium-driver
    state: present

- name: Create systemd service for DNS measurements
  copy:
    dest: /etc/systemd/system/dns-webclient-measure.service
    content: |
      [Unit]
      Description=DNS Measurement Script
      After=network.target

      [Service]
      ExecStart=/opt/dns/venv/bin/python /opt/dns/webclient.py

      # Realtime + Pinning
      CPUSchedulingPolicy=fifo
      CPUSchedulingPriority=99
      CPUAffinity=1
      Nice=-20
      LimitRTPRIO=99

      WorkingDirectory=/opt/dns
      StandardOutput=append:/var/log/dns/dns-webclient-measure.log

      User={{ measure_user }}
      Type=oneshot
      RemainAfterExit=no

      [Install]
      WantedBy=multi-user.target
    mode: "0644"

# - name: Enable dns-measure service
#   systemd:
#     name: dns-webclient-measure
#     enabled: true
#     state: stopped # Stopped initially to avoid running on boot