- name: Ensure Python 3 and pip are installed
  ansible.builtin.apt:
    name: python3-pip
    state: present
    update_cache: true
  become: true

- name: Ensure python3-venv is installed
  ansible.builtin.apt:
    name: python3-venv
    state: present
    update_cache: true
  become: true

- name: Create Python virtual environment
  command: python3 -m venv /var/log/dns/venv
  args:
    creates: /var/log/dns/venv/bin/activate

- name: Install pip in venv (ensure latest pip)
  command: /var/log/dns/venv/bin/pip install --upgrade pip setuptools wheel

- name: Install required Python packages in venv
  command: /var/log/dns/venv/bin/pip install dnspython pandas scapy selenium

- name: Ensure venv activation in .bashrc for vagrant user
  lineinfile:
    path: /home/vagrant/.bashrc
    insertafter: EOF
    line: 'source /var/log/dns/venv/bin/activate'
    state: present
    create: yes
    owner: vagrant
    group: vagrant
    mode: '0644'

- name: Copy DNS Client Script to /var/log/dns
  copy:
    src: ./../../client.py
    dest: /var/log/dns/client.py
    mode: '0644'

- name: Copy Web DNS Client Script to /var/log/dns
  copy:
    src: ./../../webclient.py
    dest: /var/log/dns/webclient.py
    mode: '0644'


- name: Copy Metadata Extractor Script to /var/log/dns
  copy:
    src: ./../../metadata_extractor.py
    dest: /var/log/dns/metadata_extractor.py
    mode: '0644'

- name: Install Chromium browser and chromedriver
  apt:
    name:
      - chromium
      - chromium-driver
    state: present