# === ansible/roles/client/tasks/main.yml ===
- name: Löse Zeitproblem komplett
  block:
    - name: Setze APT Konfiguration für Zeittoleranz
      copy:
        dest: /etc/apt/apt.conf.d/99time-fix
        content: |
          Acquire::Check-Valid-Until "false";
          Acquire::Max-ValidTime "86400";
      
    - name: Bereinige APT komplett
      shell: |
        apt-get clean
        rm -rf /var/lib/apt/lists/*
        
    - name: Forciere APT Update mit Zeittoleranz
      shell: apt-get update --allow-releaseinfo-change
      
    - name: Synchronisiere Zeit im Hintergrund
      shell: |
        timedatectl set-ntp true
        systemctl restart systemd-timesyncd
      async: 30
      poll: 0
      
  become: yes
  ignore_errors: yes
