- name: Set timezone to Europe/London
  ansible.builtin.timezone:
    name: Europe/London

- name: Install chrony for NTP
  ansible.builtin.apt:
    name: chrony
    state: present
    update_cache: yes

- name: Start and enable chrony
  ansible.builtin.service:
    name: chrony
    state: started
    enabled: yes

- name: Wait briefly until time is synchronized
  ansible.builtin.pause:
    seconds: 10

- name: Check current system time
  ansible.builtin.command: date
  register: current_time

- name: Show current time
  ansible.builtin.debug:
    var: current_time.stdout

- name: APT update
  ansible.builtin.apt:
    update_cache: yes
