- name: Restart stubby
  systemd:
    name: stubby
    state: restarted

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Restart systemd-resolved
  systemd:
    name: systemd-resolved
    state: restarted