- name: Install stubby build dependencies and runtime packages
  apt:
    name:
      - build-essential
      - cmake
      - libgetdns-dev
      - libyaml-dev
      - libssl-dev
      - libsystemd-dev
      - pkg-config
    state: present
    update_cache: yes

- name: Clone and build Stubby from source
  block:
    - name: Clone Stubby repository
      git:
        repo: https://github.com/getdnsapi/stubby.git
        dest: /tmp/stubby
        force: yes

    - name: Create build directory
      file:
        path: /tmp/stubby/build
        state: directory

    - name: Configure Stubby build
      command: cmake -DCMAKE_INSTALL_PREFIX=/usr/local ..
      args:
        chdir: /tmp/stubby/build
        creates: /tmp/stubby/build/Makefile

    - name: Build Stubby
      command: make -j{{ ansible_processor_vcpus | default(2) }}
      args:
        chdir: /tmp/stubby/build

    - name: Install Stubby
      command: make install
      args:
        chdir: /tmp/stubby/build
        creates: /usr/local/bin/stubby

    - name: Ensure Stubby config directory exists
      file:
        path: "/usr/local/etc/stubby"
        state: directory
        mode: '0755'

# - name: Configure Stubby for Quad9
#   copy:
#     dest: "/usr/local/etc/stubby/stubby.yml"
#     mode: '0644'
#     content: |
#       resolution_type: GETDNS_RESOLUTION_STUB
#       dns_transport_list:
#         - GETDNS_TRANSPORT_TLS
#       tls_authentication: GETDNS_AUTHENTICATION_REQUIRED
#       round_robin_upstreams: 1
#       idle_timeout: 10000
#       listen_addresses:
#         - 127.0.0.1@53
#         - 127.0.0.1@853
#       upstream_recursive_servers:
#         - address_data: 9.9.9.9
#           tls_auth_name: "dns.quad9.net"
#           tls_port: 853
#         - address_data: 149.112.112.112
#           tls_auth_name: "dns.quad9.net"
#           tls_port: 853
#         - address_data: 2620:fe::fe
#           tls_auth_name: "dns.quad9.net"
#           tls_port: 853
#         - address_data: 2620:fe::9
#           tls_auth_name: "dns.quad9.net"
#           tls_port: 853
#       appdata_dir: "/var/log/dns"
#       log_level: 7
#   notify: Restart stubby

- name: Configure Stubby to use Unbound proxy
  copy:
    dest: "/usr/local/etc/stubby/stubby.yml"
    mode: '0644'
    content: |
      resolution_type: GETDNS_RESOLUTION_STUB
      dns_transport_list:
        - GETDNS_TRANSPORT_TLS
      tls_authentication: GETDNS_AUTHENTICATION_NONE
      round_robin_upstreams: 1
      idle_timeout: 10000
      listen_addresses:
        - 127.0.0.1@53
      # Stubby verbindet sich mit Unbound DoT Proxy
      upstream_recursive_servers:
        - address_data: 127.0.0.1
          tls_port: 853
      appdata_dir: "/var/log/dns"
      log_level: 7
  notify: Restart stubby

  
- name: Create stubby systemd service
  copy:
    dest: /etc/systemd/system/stubby.service
    mode: '0644'
    content: |
      [Unit]
      Description=DNS Privacy Stub Resolver
      Wants=network-online.target
      After=network-online.target
      Before=nss-lookup.target
      Wants=nss-lookup.target

      [Service]
      Type=simple
      ExecStart=/usr/local/bin/stubby -C /usr/local/etc/stubby/stubby.yml
      StandardOutput=journal
      StandardError=journal

      KillSignal=SIGINT
      Restart=on-failure
      RestartSec=5
      User=stubby
      Group=stubby
      AmbientCapabilities=CAP_NET_BIND_SERVICE
      CapabilityBoundingSet=CAP_NET_BIND_SERVICE
      NoNewPrivileges=true
      MemoryDenyWriteExecute=true
      RestrictRealtime=true
      RestrictSUIDSGID=true
      ProtectControlGroups=true
      ProtectKernelModules=true
      ProtectKernelTunables=true
      ProtectSystem=strict
      ProtectHome=true
      ReadWritePaths=/var/log/dns
      PrivateDevices=true
      PrivateTmp=true

      [Install]
      WantedBy=multi-user.target
  notify: Reload systemd

- name: Create stubby user
  user:
    name: stubby
    system: yes
    shell: /usr/sbin/nologin
    home: /var/lib/stubby
    create_home: no

- name: Configure systemd-resolved to forward to Stubby
  block:
    - name: Ensure resolved drop-in directory exists
      file:
        path: /etc/systemd/resolved.conf.d
        state: directory
        mode: '0755'

    - name: Remove temporary DNS from resolved.conf
      lineinfile:
        path: /etc/systemd/resolved.conf
        line: "DNS=9.9.9.9"
        state: absent

    - name: Set Stubby as DNS resolver
      copy:
        dest: /etc/systemd/resolved.conf.d/stubby.conf
        mode: '0644'
        content: |
          [Resolve]
          DNS=127.0.0.1:853
          DNSStubListener=no
          Cache=yes
          DNSOverTLS=no
      notify: Restart systemd-resolved

- name: Make resolv.conf managed by systemd-resolved
  file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: yes
  notify: Reload systemd

- meta: flush_handlers
