- name: Install tcpdump, tshark and Zeek
  apt:
    name:
      - tcpdump
      - tshark
#     - zeek
      - vim
    state: present
    update_cache: yes

- name: Create capture directory
  file:
    path: /opt/captures
    state: directory
    mode: '0755'

- name: Note on manual usage
  debug:
    msg: "Sniffer ready. Example: tcpdump -i eth1 -w /opt/captures/dot.pcap"

- name: Set eth1 interface to promiscuous mode
  command: ip link set eth1 promisc on
  become: yes